# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32b1ef2ce5bfd7009329ba66feb63785dbca055adb743f168306ce77698ddd332fe1c4b42bcbac2df0e620126a12b55e148e8402c4a7d71c7b780c138aa08be8

test:
  secret_key_base: 6bdf36a9c8e1bcdd81e7304897597e6ec3bd1bb7ef434e714eef39bc6d5d9a1037422d55c1413fed60a1a728a5ab7ae6c2aa1b05b9c37d96e89c8b6149cddc98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
